kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-role-binding
  namespace: dev
subjects:
- kind: User
  name: john
roleRef:
  kind: Role
  name: dev-role 
  apiGroup: rbac.authorization.k8s.io
