kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prod-role-binding
  namespace: prod
subjects:
- kind: User 
  name: mary
roleRef:
  kind: Role
  name: prod-role 
  apiGroup: rbac.authorization.k8s.io
