// This file was automatically generated by lister-gen

package v1alpha1

// BlueDataClusterListerExpansion allows custom methods to be added to
// BlueDataClusterLister.
type BlueDataClusterListerExpansion interface{}

// BlueDataClusterNamespaceListerExpansion allows custom methods to be added to
// BlueDataClusterNamespaceLister.
type BlueDataClusterNamespaceListerExpansion interface{}
