apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: prod
spec:
  hard:
    limits.cpu: "20"
    limits.memory : "32212254720"
    glusterfs-storage.storageclass.storage.k8s.io/requests.storage: "536870912000"
