apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{{{NAMESPACE}}}}
spec:
  hard:
    limits.cpu: "{{{{CPU}}}}"
    limits.memory : "{{{{MEMORY}}}}"
    glusterfs-storage.storageclass.storage.k8s.io/requests.storage: "{{{{STORAGE}}}}"
