apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: prod
spec:
  hard:
    limits.cpu: "20"
    limits.memory : "21474836480"
    glusterfs-storage.storageclass.storage.k8s.io/requests.storage: "322122547200"
