// This file was automatically generated by informer-gen

package v1alpha1

import (
	bluedata_v1alpha1 "bluedata-apiserver-extension/pkg/apis/bluedata/v1alpha1"
	clientset "bluedata-apiserver-extension/pkg/client/clientset_generated/clientset"
	internalinterfaces "bluedata-apiserver-extension/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "bluedata-apiserver-extension/pkg/client/listers_generated/bluedata/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BlueDataClusterInformer provides access to a shared informer and lister for
// BlueDataClusters.
type BlueDataClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BlueDataClusterLister
}

type blueDataClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBlueDataClusterInformer constructs a new informer for BlueDataCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBlueDataClusterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBlueDataClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBlueDataClusterInformer constructs a new informer for BlueDataCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBlueDataClusterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BluedataV1alpha1().BlueDataClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BluedataV1alpha1().BlueDataClusters(namespace).Watch(options)
			},
		},
		&bluedata_v1alpha1.BlueDataCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *blueDataClusterInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBlueDataClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *blueDataClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bluedata_v1alpha1.BlueDataCluster{}, f.defaultInformer)
}

func (f *blueDataClusterInformer) Lister() v1alpha1.BlueDataClusterLister {
	return v1alpha1.NewBlueDataClusterLister(f.Informer().GetIndexer())
}
