// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "bluedata-apiserver-extension/pkg/client/informers_generated/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BlueDataClusters returns a BlueDataClusterInformer.
	BlueDataClusters() BlueDataClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BlueDataClusters returns a BlueDataClusterInformer.
func (v *version) BlueDataClusters() BlueDataClusterInformer {
	return &blueDataClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
