package v1alpha1

import (
	"bluedata-apiserver-extension/pkg/apis/bluedata"
	"github.com/kubernetes-sigs/kubebuilder/pkg/builders"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// Define CRDs for resources
	BlueDataClusterCRD = v1beta1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{
			Name: "bluedataclusters.bluedata.k8s.bluedata.com",
		},
		Spec: v1beta1.CustomResourceDefinitionSpec{
			Group:   "bluedata.k8s.bluedata.com",
			Version: "v1alpha1",
			Names: v1beta1.CustomResourceDefinitionNames{
				Kind:   "BlueDataCluster",
				Plural: "bluedataclusters",
			},
			Scope: "Namespaced",
			Validation: &v1beta1.CustomResourceValidation{
				OpenAPIV3Schema: &v1beta1.JSONSchemaProps{
					Type: "object",
					Properties: map[string]v1beta1.JSONSchemaProps{
						"apiVersion": v1beta1.JSONSchemaProps{Type: "string"},
						"kind":       v1beta1.JSONSchemaProps{Type: "string"},
						"metadata": v1beta1.JSONSchemaProps{
							Type: "object",
						},
						"spec": v1beta1.JSONSchemaProps{
							Type: "object",
							Properties: map[string]v1beta1.JSONSchemaProps{
								"label": v1beta1.JSONSchemaProps{
									Type: "object",
									Properties: map[string]v1beta1.JSONSchemaProps{
										"description": v1beta1.JSONSchemaProps{Type: "string"},
										"name":        v1beta1.JSONSchemaProps{Type: "string"},
									},
								},
								"nodegroup": v1beta1.JSONSchemaProps{
									Type:       "object",
									Properties: map[string]v1beta1.JSONSchemaProps{},
								},
							},
						},
						"status": v1beta1.JSONSchemaProps{
							Type:       "object",
							Properties: map[string]v1beta1.JSONSchemaProps{},
						},
					},
				},
			},
		},
	}
	/*
	   JSON Schema
	   {
	       "type": "object",
	       "properties": {
	           "apiVersion": {
	               "type": "string"
	           },
	           "kind": {
	               "type": "string"
	           },
	           "metadata": {
	               "type": "object"
	           },
	           "spec": {
	               "type": "object",
	               "properties": {
	                   "label": {
	                       "type": "object",
	                       "properties": {
	                           "description": {
	                               "type": "string"
	                           },
	                           "name": {
	                               "type": "string"
	                           }
	                       }
	                   },
	                   "nodegroup": {
	                       "type": "object"
	                   }
	               }
	           },
	           "status": {
	               "type": "object"
	           }
	       }
	   }
	*/

	// Collect CRDs in this group version
	CRDs = []v1beta1.CustomResourceDefinition{
		BlueDataClusterCRD,
	}

	// Register APIs
	bluedataBlueDataClusterStorage = builders.NewApiResource( // Resource status endpoint
		bluedata.InternalBlueDataCluster,
		BlueDataClusterSchemeFns{},
		func() runtime.Object { return &BlueDataCluster{} },     // Register versioned resource
		func() runtime.Object { return &BlueDataClusterList{} }, // Register versioned resource list
		&BlueDataClusterStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("bluedata.k8s.bluedata.com", "v1alpha1").WithResources(
		bluedataBlueDataClusterStorage,
		builders.NewApiResource( // Resource status endpoint
			bluedata.InternalBlueDataClusterStatus,
			BlueDataClusterSchemeFns{},
			func() runtime.Object { return &BlueDataCluster{} },     // Register versioned resource
			func() runtime.Object { return &BlueDataClusterList{} }, // Register versioned resource list
			&BlueDataClusterStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// BlueDataCluster Functions and Structs
//
// +k8s:deepcopy-gen=false
type BlueDataClusterSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type BlueDataClusterStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type BlueDataClusterStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type BlueDataClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlueDataCluster `json:"items"`
}
