// +build !ignore_autogenerated

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	bluedata "bluedata-apiserver-extension/pkg/apis/bluedata"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_BlueDataCluster_To_bluedata_BlueDataCluster,
		Convert_bluedata_BlueDataCluster_To_v1alpha1_BlueDataCluster,
		Convert_v1alpha1_BlueDataClusterList_To_bluedata_BlueDataClusterList,
		Convert_bluedata_BlueDataClusterList_To_v1alpha1_BlueDataClusterList,
		Convert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec,
		Convert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec,
		Convert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus,
		Convert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus,
		Convert_v1alpha1_BlueDataClusterStatusStrategy_To_bluedata_BlueDataClusterStatusStrategy,
		Convert_bluedata_BlueDataClusterStatusStrategy_To_v1alpha1_BlueDataClusterStatusStrategy,
		Convert_v1alpha1_BlueDataClusterStrategy_To_bluedata_BlueDataClusterStrategy,
		Convert_bluedata_BlueDataClusterStrategy_To_v1alpha1_BlueDataClusterStrategy,
	)
}

func autoConvert_v1alpha1_BlueDataCluster_To_bluedata_BlueDataCluster(in *BlueDataCluster, out *bluedata.BlueDataCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BlueDataCluster_To_bluedata_BlueDataCluster is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataCluster_To_bluedata_BlueDataCluster(in *BlueDataCluster, out *bluedata.BlueDataCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataCluster_To_bluedata_BlueDataCluster(in, out, s)
}

func autoConvert_bluedata_BlueDataCluster_To_v1alpha1_BlueDataCluster(in *bluedata.BlueDataCluster, out *BlueDataCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_bluedata_BlueDataCluster_To_v1alpha1_BlueDataCluster is an autogenerated conversion function.
func Convert_bluedata_BlueDataCluster_To_v1alpha1_BlueDataCluster(in *bluedata.BlueDataCluster, out *BlueDataCluster, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataCluster_To_v1alpha1_BlueDataCluster(in, out, s)
}

func autoConvert_v1alpha1_BlueDataClusterList_To_bluedata_BlueDataClusterList(in *BlueDataClusterList, out *bluedata.BlueDataClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]bluedata.BlueDataCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlueDataClusterList_To_bluedata_BlueDataClusterList is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataClusterList_To_bluedata_BlueDataClusterList(in *BlueDataClusterList, out *bluedata.BlueDataClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataClusterList_To_bluedata_BlueDataClusterList(in, out, s)
}

func autoConvert_bluedata_BlueDataClusterList_To_v1alpha1_BlueDataClusterList(in *bluedata.BlueDataClusterList, out *BlueDataClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BlueDataCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_bluedata_BlueDataClusterList_To_v1alpha1_BlueDataClusterList is an autogenerated conversion function.
func Convert_bluedata_BlueDataClusterList_To_v1alpha1_BlueDataClusterList(in *bluedata.BlueDataClusterList, out *BlueDataClusterList, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataClusterList_To_v1alpha1_BlueDataClusterList(in, out, s)
}

func autoConvert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec(in *BlueDataClusterSpec, out *bluedata.BlueDataClusterSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec(in *BlueDataClusterSpec, out *bluedata.BlueDataClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataClusterSpec_To_bluedata_BlueDataClusterSpec(in, out, s)
}

func autoConvert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec(in *bluedata.BlueDataClusterSpec, out *BlueDataClusterSpec, s conversion.Scope) error {
	return nil
}

// Convert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec is an autogenerated conversion function.
func Convert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec(in *bluedata.BlueDataClusterSpec, out *BlueDataClusterSpec, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataClusterSpec_To_v1alpha1_BlueDataClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus(in *BlueDataClusterStatus, out *bluedata.BlueDataClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus(in *BlueDataClusterStatus, out *bluedata.BlueDataClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataClusterStatus_To_bluedata_BlueDataClusterStatus(in, out, s)
}

func autoConvert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus(in *bluedata.BlueDataClusterStatus, out *BlueDataClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus is an autogenerated conversion function.
func Convert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus(in *bluedata.BlueDataClusterStatus, out *BlueDataClusterStatus, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataClusterStatus_To_v1alpha1_BlueDataClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_BlueDataClusterStatusStrategy_To_bluedata_BlueDataClusterStatusStrategy(in *BlueDataClusterStatusStrategy, out *bluedata.BlueDataClusterStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_BlueDataClusterStatusStrategy_To_bluedata_BlueDataClusterStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataClusterStatusStrategy_To_bluedata_BlueDataClusterStatusStrategy(in *BlueDataClusterStatusStrategy, out *bluedata.BlueDataClusterStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataClusterStatusStrategy_To_bluedata_BlueDataClusterStatusStrategy(in, out, s)
}

func autoConvert_bluedata_BlueDataClusterStatusStrategy_To_v1alpha1_BlueDataClusterStatusStrategy(in *bluedata.BlueDataClusterStatusStrategy, out *BlueDataClusterStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_bluedata_BlueDataClusterStatusStrategy_To_v1alpha1_BlueDataClusterStatusStrategy is an autogenerated conversion function.
func Convert_bluedata_BlueDataClusterStatusStrategy_To_v1alpha1_BlueDataClusterStatusStrategy(in *bluedata.BlueDataClusterStatusStrategy, out *BlueDataClusterStatusStrategy, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataClusterStatusStrategy_To_v1alpha1_BlueDataClusterStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_BlueDataClusterStrategy_To_bluedata_BlueDataClusterStrategy(in *BlueDataClusterStrategy, out *bluedata.BlueDataClusterStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_BlueDataClusterStrategy_To_bluedata_BlueDataClusterStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BlueDataClusterStrategy_To_bluedata_BlueDataClusterStrategy(in *BlueDataClusterStrategy, out *bluedata.BlueDataClusterStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlueDataClusterStrategy_To_bluedata_BlueDataClusterStrategy(in, out, s)
}

func autoConvert_bluedata_BlueDataClusterStrategy_To_v1alpha1_BlueDataClusterStrategy(in *bluedata.BlueDataClusterStrategy, out *BlueDataClusterStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_bluedata_BlueDataClusterStrategy_To_v1alpha1_BlueDataClusterStrategy is an autogenerated conversion function.
func Convert_bluedata_BlueDataClusterStrategy_To_v1alpha1_BlueDataClusterStrategy(in *bluedata.BlueDataClusterStrategy, out *BlueDataClusterStrategy, s conversion.Scope) error {
	return autoConvert_bluedata_BlueDataClusterStrategy_To_v1alpha1_BlueDataClusterStrategy(in, out, s)
}
