// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataCluster) DeepCopyInto(out *BlueDataCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataCluster.
func (in *BlueDataCluster) DeepCopy() *BlueDataCluster {
	if in == nil {
		return nil
	}
	out := new(BlueDataCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueDataCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataClusterList) DeepCopyInto(out *BlueDataClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlueDataCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataClusterList.
func (in *BlueDataClusterList) DeepCopy() *BlueDataClusterList {
	if in == nil {
		return nil
	}
	out := new(BlueDataClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueDataClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataClusterSpec) DeepCopyInto(out *BlueDataClusterSpec) {
	*out = *in
	out.Label = in.Label
	in.Nodegroup.DeepCopyInto(&out.Nodegroup)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataClusterSpec.
func (in *BlueDataClusterSpec) DeepCopy() *BlueDataClusterSpec {
	if in == nil {
		return nil
	}
	out := new(BlueDataClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataClusterStatus) DeepCopyInto(out *BlueDataClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataClusterStatus.
func (in *BlueDataClusterStatus) DeepCopy() *BlueDataClusterStatus {
	if in == nil {
		return nil
	}
	out := new(BlueDataClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataLabel) DeepCopyInto(out *BlueDataLabel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataLabel.
func (in *BlueDataLabel) DeepCopy() *BlueDataLabel {
	if in == nil {
		return nil
	}
	out := new(BlueDataLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataNodegroup) DeepCopyInto(out *BlueDataNodegroup) {
	*out = *in
	if in.RoleConfigs != nil {
		in, out := &in.RoleConfigs, &out.RoleConfigs
		*out = make([]BlueDataNodegroupRoleConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataNodegroup.
func (in *BlueDataNodegroup) DeepCopy() *BlueDataNodegroup {
	if in == nil {
		return nil
	}
	out := new(BlueDataNodegroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueDataNodegroupRoleConfig) DeepCopyInto(out *BlueDataNodegroupRoleConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueDataNodegroupRoleConfig.
func (in *BlueDataNodegroupRoleConfig) DeepCopy() *BlueDataNodegroupRoleConfig {
	if in == nil {
		return nil
	}
	out := new(BlueDataNodegroupRoleConfig)
	in.DeepCopyInto(out)
	return out
}
